//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appacker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appacker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack!.
        /// </summary>
        internal static string btnPackText {
            get {
                return ResourceManager.GetString("btnPackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing....
        /// </summary>
        internal static string btnPackTextPacking1 {
            get {
                return ResourceManager.GetString("btnPackTextPacking1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string btnPackTextPacking2 {
            get {
                return ResourceManager.GetString("btnPackTextPacking2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the application folder here.
        /// </summary>
        internal static string cueAppDirPath {
            get {
                return ResourceManager.GetString("cueAppDirPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit from main executable.
        /// </summary>
        internal static string cueFileDescription {
            get {
                return ResourceManager.GetString("cueFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select main executable.
        /// </summary>
        internal static string cueMainExe {
            get {
                return ResourceManager.GetString("cueMainExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select save location.
        /// </summary>
        internal static string cuePackExePath {
            get {
                return ResourceManager.GetString("cuePackExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password.
        /// </summary>
        internal static string cuePassword {
            get {
                return ResourceManager.GetString("cuePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing aborted.
        /// </summary>
        internal static string errorCaption {
            get {
                return ResourceManager.GetString("errorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments are missing..
        /// </summary>
        internal static string errorCode1 {
            get {
                return ResourceManager.GetString("errorCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacker.exe is missing..
        /// </summary>
        internal static string errorCode2 {
            get {
                return ResourceManager.GetString("errorCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory with the application is missing..
        /// </summary>
        internal static string errorCode3 {
            get {
                return ResourceManager.GetString("errorCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main executable is missing inside the application directory..
        /// </summary>
        internal static string errorCode4 {
            get {
                return ResourceManager.GetString("errorCode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package save location is invalid..
        /// </summary>
        internal static string errorCode5 {
            get {
                return ResourceManager.GetString("errorCode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File access is denied..
        /// </summary>
        internal static string errorCode6 {
            get {
                return ResourceManager.GetString("errorCode6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string errorCodeUnknown {
            get {
                return ResourceManager.GetString("errorCodeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing was not performed. Packer has exited with code.
        /// </summary>
        internal static string errorText {
            get {
                return ResourceManager.GetString("errorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated package size: .
        /// </summary>
        internal static string labSizeText {
            get {
                return ResourceManager.GetString("labSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When application is finished, its files are deleted from a temp folder without saving.
        ///Changes to the app files won&apos;t be saved (e.g. app settings)..
        /// </summary>
        internal static string repackOffDescr {
            get {
                return ResourceManager.GetString("repackOffDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When application is finished, all its files will be packed back and packed .exe will be replaced.
        ///Any changes will be saved (e.g. app settings)..
        /// </summary>
        internal static string repackOnDescr {
            get {
                return ResourceManager.GetString("repackOnDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can redirect stdout of a packed application and use it via command line,
        ///BUT unpacker console will appear for a split-second before becoming invisible.
        /// </summary>
        internal static string windowlessOffDescr {
            get {
                return ResourceManager.GetString("windowlessOffDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacker daemon is completely invisible,
        ///BUT you can not redirect stdout of a packed application.
        /// </summary>
        internal static string windowlessOnDescr {
            get {
                return ResourceManager.GetString("windowlessOnDescr", resourceCulture);
            }
        }
    }
}
